# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
#sudo: false
sudo: required  # to allow r_binary_packages
cache: packages
env: _R_CHECK_FORCE_SUGGESTS_=false

# libraries necessary for RNetCDF and ncdf4
addons:
  apt:
    packages:
      - libnetcdf-dev
      - libudunits2-dev

# REddyProc will be installed from github or CRAN
# in order to be faster, install REddyProc prerequisites as binaries
#r_binary_packages:
#  - ncdf4
#  - RNetCDF
#  - dplyr
#  - purrr
#  - tibble
#  - minpack.lm
#  - segmented
#  - mlegp
#  - testthat
#  - knitr
